parameters:
#    bionic_university_student.example.class: BionicUniversity\StudentBundle\Example

services:
#    bionic_university_student.example:
#        class: %bionic_university_student.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
