BionicUniversity\StudentBundle\Entity\Student:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        firstName:
            type: string
        lastName:
            type: string
        email:
            type: string
            unique: true
    manyToOne:
        cafedra:
            targetEntity: BionicUniversity\StudentBundle\Entity\Cafedra
            inversedBy: students
    lifecycleCallbacks: {  }
